# Generated by Django 3.2.9 on 2021-12-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_id', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_name', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_email', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_tel', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_prof', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_address', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_bankacc', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_bankname', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_next_visit', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('tea_doc_cv', models.FileField(blank=True, null=True, upload_to='tea_doc/cv/')),
                ('tea_doc_card', models.FileField(blank=True, null=True, upload_to='tea_doc/card/')),
                ('tea_doc_bankacc', models.FileField(blank=True, null=True, upload_to='tea_doc/bankacc/')),
                ('tea_doc_agree', models.FileField(blank=True, null=True, upload_to='tea_doc/agree/')),
                ('tea_doc_sign', models.FileField(blank=True, null=True, upload_to='tea_doc/sign/')),
            ],
            options={
                'ordering': ['tea_name'],
            },
        ),
    ]
