# Generated by Django 3.2.9 on 2021-12-01 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '__first__'),
        ('school', '__first__'),
        ('material', '__first__'),
        ('teacher', '__first__'),
        ('classstatd', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(blank=True, max_length=120, null=True)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('class_cate', models.CharField(blank=True, max_length=120, null=True)),
                ('class_minicate', models.CharField(blank=True, max_length=120, null=True)),
                ('class_stat', models.CharField(blank=True, max_length=120, null=True)),
                ('class_stunum', models.CharField(blank=True, max_length=120, null=True)),
                ('class_time', models.CharField(blank=True, max_length=120, null=True)),
                ('class_place', models.CharField(blank=True, max_length=120, null=True)),
                ('class_count', models.IntegerField(blank=True, default=1, null=True)),
                ('class_sch', models.CharField(max_length=120, null=True)),
                ('class_tea', models.CharField(blank=True, max_length=120, null=True)),
                ('memo', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_confirm', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp_progress', models.DateTimeField(blank=True, null=True)),
                ('user_progress', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp_memo', models.DateTimeField(blank=True, null=True)),
                ('user_memo', models.CharField(blank=True, max_length=120, null=True)),
                ('schtea', models.CharField(blank=True, max_length=120, null=True)),
                ('class_3', models.CharField(blank=True, max_length=120, null=True)),
                ('class_price', models.IntegerField(blank=True, default=0, null=True)),
                ('class_tea_price', models.IntegerField(blank=True, default=0, null=True)),
                ('class_order', models.BooleanField(default=False)),
                ('class_deli', models.BooleanField(default=False)),
                ('class_pay', models.CharField(blank=True, max_length=120, null=True)),
                ('class_mani', models.BooleanField(default=False)),
                ('class_div', models.BooleanField(default=False)),
                ('class_taken', models.BooleanField(default=False)),
                ('class_done', models.BooleanField(default=False)),
                ('class_re_done', models.BooleanField(default=False)),
                ('class_doc_plan', models.BooleanField(default=False)),
                ('class_doc_preestim', models.BooleanField(default=False)),
                ('class_doc_preestim_meth', models.CharField(blank=True, max_length=120, null=True)),
                ('class_doc_tea', models.BooleanField(default=False)),
                ('class_doc_finestim', models.BooleanField(default=False)),
                ('class_cal_meth', models.CharField(blank=True, max_length=120, null=True)),
                ('class_deposit_check', models.BooleanField(default=False)),
                ('class_process', models.CharField(blank=True, default='진행X', max_length=120, null=True)),
                ('class_file_preestim', models.FileField(blank=True, null=True, upload_to='class_file/preestim/')),
                ('class_file_plan', models.FileField(blank=True, null=True, upload_to='class_file/plan/')),
                ('class_file_tea', models.FileField(blank=True, null=True, upload_to='class_file/tea/')),
                ('class_file_finestim', models.FileField(blank=True, null=True, upload_to='class_file/finestim/')),
                ('class_file_cal', models.FileField(blank=True, null=True, upload_to='class_file/cal/')),
                ('class_tea_inout', models.CharField(blank=True, default='반출미완료', max_length=120, null=True)),
                ('class_tea_inout_date', models.DateTimeField(blank=True, null=True)),
                ('class_schkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolinfo')),
                ('class_statkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classstatd.classstatinfo')),
                ('class_teakey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherinfo')),
                ('schteakey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolteainfo')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacherpay_monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_year', models.IntegerField(blank=True, null=True)),
                ('tp_month', models.IntegerField(blank=True, null=True)),
                ('tp_monthly_pay', models.IntegerField(blank=True, null=True)),
                ('tp_teakey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacherpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_pay', models.IntegerField(blank=True, null=True)),
                ('tp_tax', models.IntegerField(blank=True, null=True)),
                ('tp_atax', models.IntegerField(blank=True, null=True)),
                ('tp_content', models.CharField(blank=True, max_length=120, null=True)),
                ('tp_classkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classd.classinfo')),
                ('tp_monthly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classd.teacherpay_monthly')),
            ],
        ),
        migrations.CreateModel(
            name='Teacherinoutinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('inout_date', models.DateTimeField(blank=True, null=True)),
                ('inout_status', models.CharField(default='미완료', max_length=100)),
                ('inout_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classd.classinfo')),
                ('inout_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='dyna_mat_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.CharField(blank=True, max_length=120, null=True)),
                ('dyna_mat_num', models.CharField(blank=True, default='0', max_length=120, null=True)),
                ('status', models.CharField(blank=True, default='준비중', max_length=120, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('mat_manu_done', models.BooleanField(default=False)),
                ('mat_div_done', models.BooleanField(default=False)),
                ('tool_re', models.BooleanField(default=False)),
                ('dyna_mat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classd.classinfo')),
                ('mat_dyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialinfo')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
