# Generated by Django 3.2.9 on 2021-12-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materialinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_id', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_name', models.CharField(max_length=120, null=True)),
                ('mat_shop', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_link', models.CharField(blank=True, max_length=500, null=True)),
                ('mat_price', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_loc', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_inven', models.FloatField(blank=True, default=0, null=True)),
                ('mat_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_memo', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
