# Generated by Django 3.2.9 on 2021-12-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classstatinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=120, null=True)),
                ('class_title', models.CharField(max_length=120, null=True)),
                ('class_detail', models.TextField(blank=True, null=True)),
                ('class_file_recipe', models.FileField(blank=True, null=True, upload_to='class_data/recipe/')),
                ('class_file_image', models.FileField(blank=True, null=True, upload_to='class_data/class_image/')),
            ],
        ),
        migrations.CreateModel(
            name='stat_mat_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_mat_str', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_stat', models.CharField(blank=True, max_length=120, null=True)),
                ('stat_mat_amount', models.FloatField(blank=True, null=True)),
                ('stat_mat_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('memo', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_statkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialinfo')),
                ('stat_mat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classstatd.classstatinfo')),
            ],
        ),
    ]
