# Generated by Django 3.2.9 on 2021-12-01 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('order_price', models.IntegerField(blank=True, null=True)),
                ('order_deli_price', models.IntegerField(blank=True, null=True)),
                ('order_meth', models.CharField(blank=True, max_length=120, null=True)),
                ('order_acc', models.CharField(blank=True, max_length=120, null=True)),
                ('order_done', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('order_user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('shop', models.CharField(blank=True, max_length=120, null=True)),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('deli_amount', models.FloatField(blank=True, null=True)),
                ('deli_check_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('deli_state', models.CharField(blank=True, default='결제대기중', max_length=120, null=True)),
                ('mat_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialinfo')),
                ('order_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
